### ISSUE TITLE
cf/templates/cf-lamb.yml links to file in cf-release submodule

### ISSUE THREAD

**Issue by weberstephanhd** [cloudfoundry-incubator/bosh-workspace#51]
Hi,

It seems that bosh-workspace does not do a "git submodule update --init" when populating the .releases folder with the release's versions. 

As described in the BWS-README.md the templates folder of the boshworkspace contains a link with name "cf" to ".releases/cf/templates templates/cf"
In cf-release's templates folder is a link ".../.releases/cf/templates/cf-lamb.yml" to a cf submodule's file ".../.releases/cf/src/loggregator/manifest-templates/cf-lamb.yml". This file does not exist if the submodules were not updated and initialized after checkout.

Will 0.9.0 solve this "uninitialized releases' submodules" problem?
My deployment file looks like https://gist.github.com/weberstephanhd/4c31c6690c02fa6bbb26 

Best regards, Stephan

**Comment by rkoster** [comment]
This issue is a duplicate of https://github.com/cloudfoundry-incubator/bosh-workspace/issues/42, but thanks for reporting. In 0.9.0 (for which no final release has been published yet), ruby-git has been replaced by rugged. I still have to figure out how to efficiently initialise the needed submodules.

**Comment by weberstephanhd** [comment]
Oh, I see - sounds like a solution isn't that far away ;-)
As this is a duplicate I close it.
